# Localization
apiVersion: delivery.ocm.software/v1alpha1
kind: Localization
metadata:
  name: backend-localization
  namespace: ocm-system
spec:
  configRef:
    kind: ComponentVersion
    name: multiocmpodify2
    namespace: ocm-system
    resourceRef:
      name: config
      referencePath:
      - name: backend
      version: v1.1.7
  interval: 10m0s
  sourceRef:
    kind: ComponentVersion
    name: multiocmpodify2
    namespace: ocm-system
    resourceRef:
      name: manifests
      referencePath:
      - name: backend
      version: v1.1.7
