apiVersion: delivery.ocm.software/v1alpha1
kind: Configuration
metadata:
  name: cache-configuration
  namespace: ocm-system
spec:
  configRef:
    kind: ComponentVersion
    name: multiocmpodify2
    namespace: ocm-system
    resourceRef:
      name: config
      referencePath:
      - name: cache
      version: v1.1.8
  interval: 10m0s
  sourceRef:
    apiVersion: delivery.ocm.software/v1alpha1
    kind: Localization
    name: cache-localization
    namespace: ocm-system