apiVersion: delivery.ocm.software/v1alpha1
kind: ComponentVersion
metadata:
  name: podinfo
  namespace: ocm-system
spec:
  interval: 10m0s
  component: github.com/sidhishruti22/multipodinfo
  version:
    semver: v1.0.0
  repository:
    url: ghcr.io/sidhishruti22
    secretRef:
      name: creds
  verify: []
  references:
    expand: true
