apiVersion: delivery.ocm.software/v1alpha1
kind: Resource
metadata:
  name: sidhii-podinfo-deployment
  namespace: ocm-system
spec:
  interval: 1m0s
  sourceRef:
    kind: ComponentVersion
    name: podinfo
    resourceRef:
      name: deploy
      version: latest
