apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/sidhishruti22/frontend
  provider:
    name: sidhishruti22
  version: v1.1.7
repositoryContexts: []
spec:
  resources:
  - access:
      localReference: sha256.78eacf92e74960f0bf4e234bdb694c3bf34deb60aa3d8170dcaadac137dfc743
      mediaType: application/yaml
      type: localBlob
    name: config
    relation: local
    type: configdata.ocm.software
    version: v1.1.7
  - access:
      imageReference: ghcr.io/stefanprodan/podinfo:6.2.0
      type: ociArtifact
    name: image
    relation: external
    type: ociImage
    version: 6.2.0
  - access:
      localReference: sha256.6b5a2ca49e46d21fba3650345f8cce87e743342fad9fbf03908ddc94634353ea
      mediaType: application/x-tar
      type: localBlob
    name: manifests
    relation: local
    type: kustomize.ocm.fluxcd.io
    version: v1.1.7
