apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/sidhishruti22/frontend
  provider:
    name: sidhishruti22
  version: v1.1.8
repositoryContexts: []
spec:
  resources:
  - access:
      localReference: sha256.78eacf92e74960f0bf4e234bdb694c3bf34deb60aa3d8170dcaadac137dfc743
      mediaType: application/yaml
      type: localBlob
    name: config
    relation: local
    type: configdata.ocm.software
    version: v1.1.8
  - access:
      imageReference: ghcr.io/stefanprodan/podinfo:6.2.0
      type: ociArtifact
    name: image
    relation: external
    type: ociImage
    version: 6.2.0
  - access:
      localReference: sha256.681e423b3af4980f13e369857f3401b00936a4301db7742a0962ce35805f07bd
      mediaType: application/x-tar
      type: localBlob
    name: manifests
    relation: local
    type: kustomize.ocm.fluxcd.io
    version: v1.1.8
