apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/sidhishruti22/backend
  provider:
    name: sidhishruti22
  version: v1.1.5
repositoryContexts: []
spec:
  resources:
  - access:
      localReference: sha256.60ed79064c9728a8ede1f83d2a32c21d4546262dbf1a7ca77e9e761d5b2e52b9
      mediaType: application/yaml
      type: localBlob
    name: config
    relation: local
    type: configdata.ocm.software
    version: v1.1.5
  - access:
      imageReference: ghcr.io/stefanprodan/podinfo:6.2.0
      type: ociArtifact
    name: image
    relation: external
    type: ociImage
    version: 6.2.0
  - access:
      localReference: sha256.33e9e166ce6a5a0b76a7b81cc002fafd77d7cd82f4ee0ba3b38d6b5d4a1f85d2
      mediaType: application/x-tar
      type: localBlob
    name: manifests
    relation: local
    type: Directory
    version: v1.1.5
