apiVersion: ocm.software/v3alpha1
kind: ComponentVersion
metadata:
  name: github.com/sidhishruti22/backend
  provider:
    name: sidhishruti22
  version: v1.1.6
repositoryContexts: []
spec:
  resources:
  - access:
      localReference: sha256.4ecb22c27c416883124306cdad5ddae8f714961e33b47a96dfaf0c551309a55f
      mediaType: application/yaml
      type: localBlob
    name: config
    relation: local
    type: configdata.ocm.software
    version: v1.1.6
  - access:
      imageReference: ghcr.io/stefanprodan/podinfo:6.2.0
      type: ociArtifact
    name: image
    relation: external
    type: ociImage
    version: 6.2.0
  - access:
      localReference: sha256.1b51f61607c96d690f5a541212657583812331df61b98686e0a2c8dc61b909c3
      mediaType: application/x-tar
      type: localBlob
    name: manifests
    relation: local
    type: Directory
    version: v1.1.6
